Neos:
  Neos:
    modules:
      management:
        submodules:
          workspace:
            label: 'Neos.Workspace.Ui:Main:workspaces.label'
            controller: 'Neos\Workspace\Ui\Controller\WorkspaceController'
            description: 'Neos.Workspace.Ui:Main:workspaces.description'
            icon: fas fa-th-large
            mainStylesheet: 'Lite'
            additionalResources:
              javaScripts:
                'Neos.Workspace.Ui': 'resource://Neos.Workspace.Ui/Public/Scripts/htmx.min.js'
              styleSheets:
                'Neos.Workspace.Ui': 'resource://Neos.Workspace.Ui/Public/Styles/Module.css'

    userInterface:
      translation:
        autoInclude:
          Neos.Workspace.Ui:
            - Main
